// =====================================================
// DADOS INICIAIS - Importados da planilha ANIVERSARIANTES_2.xlsm
// =====================================================

const INITIAL_DATA = [
  { name: "Robson Lago",                       dob: "2002-01-23", phone: "359970-24808" },
  { name: "Robson T Lago / Ronivan T Lago",    dob: "1967-04-26", phone: "3599421-507" },
  { name: "Caroline Moreira Dos Santos",       dob: "2002-02-16", phone: "35998872365" },
  { name: "Maria Aparecida Dos Reis",          dob: "1967-07-12", phone: "" },
  { name: "Juliana Moreira Barbosa",           dob: "1980-12-20", phone: "35998346118" },
  { name: "Roberto André Dos Santos",          dob: "1974-08-05", phone: "35999067928" },
  { name: "Nilceia Barbosa Moreira",           dob: "1959-08-05", phone: "35999620407" },
  { name: "Walter Moreira Barbosa",            dob: "1944-06-26", phone: "" },
  { name: "Walter Giovani Moreira Barbosa",    dob: "1984-09-01", phone: "35999622400" },
  { name: "Helena e Giovana",                  dob: "2019-02-18", phone: "" },
  { name: "Patricia Helena De Souza Moreira",  dob: "1981-04-14", phone: "" },
  { name: "Ivanise e Victor",                  dob: "1981-02-16", phone: "" },
  { name: "Fernanda",                          dob: "",           phone: "" },
  { name: "Antonio Luciano Dos Reis",          dob: "",           phone: "" },
  { name: "Tia Creusa",                        dob: "1950-04-14", phone: "" },
  { name: "Lucas Eduardo Dos Santos Paulino",  dob: "2005-01-24", phone: "" },
  { name: "Otavio Augusto Dos Santos Paulino", dob: "2009-06-02", phone: "" },
  { name: "Tio Francisco",                     dob: "",           phone: "" },
  { name: "Tia Marcia",                        dob: "",           phone: "" },
  { name: "Tio Rovilson",                      dob: "",           phone: "" },
  { name: "Fabiana",                           dob: "",           phone: "" },
  { name: "Maria Bandeira",                    dob: "",           phone: "" },
  { name: "Lucas - Maria",                     dob: "",           phone: "" },
  { name: "Helena - Maria",                    dob: "",           phone: "" },
  { name: "Gabriel - Maria",                   dob: "",           phone: "" },
  { name: "Marcos - Maria",                    dob: "",           phone: "" },
  { name: "Dedé - Maria",                      dob: "",           phone: "" },
  { name: "Tia Ana Paula",                     dob: "",           phone: "" },
  { name: "Tio Grinho",                        dob: "",           phone: "" },
  { name: "Leticinha",                         dob: "2004-03-19", phone: "" },
  { name: "Douglas",                           dob: "",           phone: "" },
  { name: "Marquinho",                         dob: "1980-06-13", phone: "" },
  { name: "Michele",                           dob: "1982-08-27", phone: "" },
  { name: "Emanuel Leoterio Hipolito",         dob: "2017-12-08", phone: "" },
  { name: "Larissa Rodrigues Dos Santos",      dob: "2015-12-13", phone: "" },
  { name: "Preto",                             dob: "",           phone: "" },
  { name: "Pitinho",                           dob: "",           phone: "" },
  { name: "Tia Rosa",                          dob: "",           phone: "" },
  { name: "Edvania",                           dob: "",           phone: "" },
  { name: "Tio Derli",                         dob: "",           phone: "" },
  { name: "Zilda",                             dob: "",           phone: "" },
  { name: "Tio Paulinho",                      dob: "1976-08-04", phone: "" },
  { name: "Tia Mariana",                       dob: "1980-03-02", phone: "" },
  { name: "Lorena",                            dob: "2018-05-10", phone: "" },
  { name: "Samuel - Bandeira",                 dob: "",           phone: "" },
  { name: "Sara - Bandeira",                   dob: "",           phone: "" },
  { name: "Angela Figueiredo",                 dob: "",           phone: "" },
  { name: "Paula Figueiredo",                  dob: "",           phone: "" },
  { name: "Lucia Figueiredo",                  dob: "1970-04-12", phone: "" },
  { name: "Tania Rodrigues",                   dob: "",           phone: "" },
  { name: "Paulo Rodrigues",                   dob: "",           phone: "" },
  { name: "Neto",                              dob: "2003-01-24", phone: "" },
  { name: "Tia Fatima",                        dob: "",           phone: "" },
  { name: "Ritinha",                           dob: "1995-10-23", phone: "" },
  { name: "João",                              dob: "1990-10-17", phone: "" },
  { name: "Luana Barros",                      dob: "2000-11-29", phone: "" },
  { name: "Guilherme Barros",                  dob: "1995-11-08", phone: "" },
  { name: "Otavio Barros",                     dob: "",           phone: "" },
  { name: "Denilson",                          dob: "",           phone: "" },
  { name: "Rosimeire",                         dob: "",           phone: "" },
  { name: "Rosemeire Pai",                     dob: "",           phone: "" },
  { name: "Tia Valéria",                       dob: "",           phone: "" },
  { name: "Vinicius Moreira",                  dob: "1984-02-16", phone: "" },
  { name: "João Luiz",                         dob: "",           phone: "" },
  { name: "Lidiane",                           dob: "2002-03-07", phone: "" }
];
